version: "3.9"

services:
    web:
        build: .
        command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
        container_name: social-media
        volumes:
            - .:/app
        ports:
            - "8000:8000"
        depends_on:
            - localhost
            - redis
        environment:
            POSTGRES_DB: db.postgresql
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: lmao
            REDIS_URL: redis://redis:6379/1

    localhost:
        image: postgres:latest
        container_name: pp-postgres
        environment:
            POSTGRES_DB: db.postgresql
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: lmao
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

    redis:
        image: redis:latest
        container_name: pp-redis
        ports:
            - "6379:6379"

volumes:
    postgres_data:
